// File generated by FlutterFire CLI & customized for Food Recognizer App.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'food-recognizer-app-demo',
    authDomain: 'food-recognizer-app-demo.firebaseapp.com',
    storageBucket: 'food-recognizer-app-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42HIRGEqLJ9tzw8P9fcDRpT_QWjpbMbE',
    appId: '1:1097844958640:android:4832ff958fd01d0042a275',
    messagingSenderId: '1097844958640',
    projectId: 'food-recognizer-56804',
    storageBucket: 'food-recognizer-56804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQU9C0lXDzZkpY4KW0IXyYy-8xs6q7Fs',
    appId: '1:1097844958640:ios:977d383bd13246a042a275',
    messagingSenderId: '1097844958640',
    projectId: 'food-recognizer-56804',
    storageBucket: 'food-recognizer-56804.firebasestorage.app',
    iosBundleId: 'com.example.foodrecognizerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:1097844958640:ios:977d383bd13246a042a275',
    messagingSenderId: '1097844958640',
    projectId: 'food-recognizer-56804',
    storageBucket: 'food-recognizer-56804.firebasestorage.app',
    iosBundleId: 'com.example.foodrecognizerapp',
  );
}
